### PR TITLE
#171380692 Setup storybook

### PR DESCRIPTION
**Pull request by descholar-ceo**
### What does this PR ​ do​ ? 
Setup storybook

### Description of Task to be completed?
- [x] Add necessary dependencies
- [x] Creating one story of the HelloComponent

##### A.Pre-requisites : 
* To be able to test this PR locally, you need to have the following tools on your local machine:
> * You need to have [NodeJS version `6` or newer](https://nodejs.org/en/) and [npm version `6` or newer](https://www.npmjs.com/) or [yarn v1.15.0 or newer](https://yarnpkg.com/getting-started/install)
> * Your local machine needs to be able to run terminal, Powershell, or bash commands
#### B. Steps
1. Clone this repo by running `git clone https://github.com/Stackup-Rwanda/stackup2-barefoot-frontend.git`
1. Check out this branch by running the following commands:
    > `git checkout ch-setup-story-book-171380692`
1. Install all needed dependencies by running `npm install` or `yarn`
1. Start the Storybook server by running `npm storybook` or `yarn storybook`, it will automatically launch your default browser at `http://localhost:6006/?path=/story/welcome--to-storybook` ===> if it does not open automatically open your browser and go to the aforementioned URL, you should see a page looks like the following on the screenshot
Screenshot from 2020-05-18 19-04-27

===> If you see that page, that means this chore is successfully configured

[What is React Storybook?](https://spin.atomicobject.com/2018/01/24/react-storybook/)

### What are the relevant pivotal tracker stories?
[#171380692](https://www.pivotaltracker.com/n/projects/2435482/stories/171380692)

#### Hello component story
Screenshot from 2020-05-18 19-06-56

### Questions:
N/A

### CODE REVIEW

**Review by the22mastermind — APPROVED** [review]
Well done @descholar-ceo It looks good to me.
However I have a small suggestion, could you remove `npm` in this PR description to specify the use of `yarn` explicitly.
Lastly, don't forget to add your new dependencies to the README file.
Keep up the good work!

**Review by muchristian — APPROVED** [review]
Well done @descholar-ceo  all looks good with helpful links

**Review by Ugizwenayo-Divine — APPROVED** [review]
well done!!
LGTM

**Comment by descholar-ceo** [comment]
> Well done @descholar-ceo It looks good to me.
> However I have a small suggestion, could you remove `npm` in this PR description to specify the use of `yarn` explicitly.
> Lastly, don't forget to add your new dependencies to the README file.
> Keep up the good work!

@the22mastermind Thank you for the feedback:

> For the removing of npm from this PR description, I don't think if it's a good idea, because npm also can work, so since this project can be used with other people for learning purpose, so I think let's npm there so that it will be flexible for anyone

> For the addition of packages in README.md file, I have just done it, thank you for reminding me.

**Comment by kipropbrian** [comment]
Awesome, you went above and beyond what I expected. Good work.

**Pull request merged**
