### PR TITLE
#171380689 Setup code climate test coverage and codacy code quality

### PR DESCRIPTION
**Pull request by descholar-ceo**
### What does this PR ​ do​ ? 
Setup code climate test coverage and codacy code quality

### Description of Task to be completed?
- [x] Add necessary dependency (codeclimate-test-reporter)
- [x] Create script for reporting code coverage to code climate
- [x] Modify .travis.yml file to report code coverage to code climate
- [x] Add a badge for test coverage to readme.md file
- [x] Modify .gitignore file to add yarn-error.log file to exclude it from github repo
- [x] Add repo to codacy
- [x] Add .codacy.yml file to hold codacy configs
- [x] Add codacy badge to this repo
- [x] Update codeclimate settings to include the PR commenting and status update

### How should this be manually tested?
N/A

### Any background context you want to provide?
N/A

### What are the relevant pivotal tracker stories?
[#171380689](https://www.pivotaltracker.com/n/projects/2435482/stories/171380689)

### Screenshots 
N/A

### Questions:
N/A

### CODE REVIEW

**Review by the22mastermind — APPROVED** [review]
Awesome work @descholar-ceo 
Keep it up!

**Review by muchristian — APPROVED** [review]
Well done @descholar-ceo good work but i would suggest if you can add guiding links on how you have added and configured for instance codacy

**Comment by descholar-ceo** [comment]
> Well done @descholar-ceo good work but i would suggest if you can add guiding links on how you have added and configured for instance codacy

@muchristian refer to this official link of cadacy https://www.codacy.com/

**Comment by descholar-ceo** [comment]
@kipropbrian I am finished with rebasing

**Pull request merged**
